export const HEADER_ALIASES: Record<string, string[]> = {
  created_at: [
    "created_at",
    "created at",
    "created date",
    "creation date",
    "lead creation date",
    "date created",
    "created on",
    "creation time",
    "created timestamp",
    "created datetime",
    "record created",
    "entry date",
    "entry time",
    "submission date",
    "submitted at",
    "submitted on",
    "registration date",
    "registered at",
    "registered on",
    "signup date",
    "sign up date",
    "added on",
    "added at",
    "import date",
    "date",
    "timestamp",
  ],

  name: [
    "name",
    "full name",
    "customer name",
    "lead name",
    "client name",
    "person name",
    "contact name",
    "prospect name",
    "individual name",
    "applicant name",
    "user name",
    "fullname",
    "full_name",
    "display name",
    "owner name",
    "primary contact",
  ],

  email: [
    "email",
    "email address",
    "email id",
    "mail",
    "e-mail",
    "e-mail address",
    "primary email",
    "work email",
    "business email",
    "official email",
    "contact email",
    "personal email",
    "email_address",
    "emailid",
  ],

  mobile_without_country_code: [
    "phone",
    "phone number",
    "mobile",
    "mobile number",
    "contact",
    "contact number",
    "telephone",
    "telephone number",
    "cell",
    "cell number",
    "cell phone",
    "mobile no",
    "phone no",
    "contact no",
    "contact no.",
    "mobile no.",
    "phone_no",
    "mobile_no",
    "contact_number",
    "whatsapp",
    "whatsapp number",
    "calling number",
    "primary phone",
    "primary mobile",
    "office phone",
    "work phone",
    "customer phone",
    "lead phone",
    "mobile_without_country_code",
  ],

  country_code: [
    "country_code",
    "country code",
    "isd code",
    "isd",
    "dial code",
    "dialing code",
    "calling code",
    "international code",
    "country prefix",
    "phone code",
    "telephone code",
    "country dialing code",
    "phone prefix",
    "mobile country code",
  ],

  company: [
    "company",
    "company name",
    "organization",
    "organisation",
    "business",
    "business name",
    "firm",
    "firm name",
    "employer",
    "employer name",
    "office",
    "office name",
    "enterprise",
    "corporation",
    "corp",
    "brand",
    "vendor",
    "client company",
    "account",
    "account name",
    "company_name",
    "organisation name",
    "organization name",
  ],

  city: [
    "city",
    "town",
    "municipality",
    "location city",
    "city name",
    "residential city",
    "current city",
    "home city",
  ],

  state: [
    "state",
    "province",
    "region",
    "county",
    "state name",
    "state/province",
    "province name",
    "administrative region",
    "territory",
  ],

  country: [
    "country",
    "nation",
    "country name",
    "location",
    "residence country",
    "current country",
    "home country",
    "nationality country",
  ],

  lead_owner: [
    "lead owner",
    "owner",
    "assigned to",
    "assignee",
    "account owner",
    "sales rep",
    "sales representative",
    "salesperson",
    "executive",
    "relationship manager",
    "manager",
    "agent",
    "representative",
    "handler",
    "advisor",
    "consultant",
    "employee",
    "owner name",
    "assigned user",
    "assigned employee",
  ],

  crm_status: [
    "crm status",
    "status",
    "lead status",
    "customer status",
    "current status",
    "stage",
    "pipeline stage",
    "sales stage",
    "lead stage",
    "deal stage",
    "progress",
    "workflow status",
    "qualification status",
    "conversion status",
    "record status",
  ],

  crm_note: [
    "crm note",
    "note",
    "notes",
    "remarks",
    "remark",
    "comment",
    "comments",
    "observation",
    "observations",
    "description note",
    "internal note",
    "internal remarks",
    "feedback",
    "review",
    "memo",
    "summary",
    "additional notes",
    "extra notes",
    "customer note",
    "lead note",
  ],

  data_source: [
    "data source",
    "source",
    "lead source",
    "origin",
    "channel",
    "marketing source",
    "acquisition source",
    "campaign",
    "campaign source",
    "referral",
    "reference source",
    "traffic source",
    "import source",
    "platform",
    "medium",
    "source name",
  ],

  possession_time: [
    "possession",
    "possession time",
    "ownership time",
    "holding period",
    "owned since",
    "years owned",
    "duration owned",
    "ownership duration",
    "tenure",
    "time owned",
    "occupied since",
    "residency duration",
  ],

  description: [
    "description",
    "details",
    "detail",
    "additional description",
    "summary",
    "about",
    "information",
    "extra information",
    "additional information",
    "notes",
    "remarks",
    "comments",
    "explanation",
    "context",
    "overview",
    "specification",
    "specifications",
    "customer requirements",
    "lead details",
    "issue",
    "reason",
    "purpose",
    "message",
    "query",
  ],
};
